
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Frame frame1;
	private global::Gtk.Fixed Panel;
	private global::Gtk.Button Ingresar;
	private global::Gtk.Button Salir;
	private global::Gtk.Entry Pass;
	private global::Gtk.Entry usuario;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.Panel = new global::Gtk.Fixed ();
		this.Panel.Name = "Panel";
		this.Panel.HasWindow = false;
		// Container child Panel.Gtk.Fixed+FixedChild
		this.Ingresar = new global::Gtk.Button ();
		this.Ingresar.CanFocus = true;
		this.Ingresar.Name = "Ingresar";
		this.Ingresar.UseUnderline = true;
		this.Ingresar.Label = global::Mono.Unix.Catalog.GetString ("Ingresar");
		this.Panel.Add (this.Ingresar);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.Panel [this.Ingresar]));
		w1.X = 200;
		w1.Y = 200;
		// Container child Panel.Gtk.Fixed+FixedChild
		this.Salir = new global::Gtk.Button ();
		this.Salir.CanFocus = true;
		this.Salir.Name = "Salir";
		this.Salir.UseUnderline = true;
		this.Salir.Label = global::Mono.Unix.Catalog.GetString ("   Salir  ");
		this.Panel.Add (this.Salir);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.Panel [this.Salir]));
		w2.X = 100;
		w2.Y = 200;
		// Container child Panel.Gtk.Fixed+FixedChild
		this.Pass = new global::Gtk.Entry ();
		this.Pass.CanFocus = true;
		this.Pass.Name = "Pass";
		this.Pass.IsEditable = true;
		this.Pass.InvisibleChar = '●';
		this.Panel.Add (this.Pass);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.Panel [this.Pass]));
		w3.X = 100;
		w3.Y = 157;
		// Container child Panel.Gtk.Fixed+FixedChild
		this.usuario = new global::Gtk.Entry ();
		this.usuario.CanFocus = true;
		this.usuario.Name = "usuario";
		this.usuario.IsEditable = true;
		this.usuario.InvisibleChar = '●';
		this.Panel.Add (this.usuario);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.Panel [this.usuario]));
		w4.X = 100;
		w4.Y = 100;
		// Container child Panel.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Usuario");
		this.Panel.Add (this.label1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.Panel [this.label1]));
		w5.X = 100;
		w5.Y = 79;
		// Container child Panel.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Contraseña");
		this.Panel.Add (this.label2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.Panel [this.label2]));
		w6.X = 100;
		w6.Y = 139;
		this.frame1.Add (this.Panel);
		this.Add (this.frame1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 338;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Ingresar.Clicked += new global::System.EventHandler (this.OnIngresarClicked);
		this.Salir.Clicked += new global::System.EventHandler (this.OnSalirClicked);
	}
}
